sonar.projectKey=eventora_frontend
sonar.projectName=Eventora Frontend
sonar.projectVersion=0.0.1-SNAPSHOT
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx,**/node_modules/**,**/.next/**
sonar.tests=cypress
sonar.test.inclusions=**/*.cy.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
