version: '3.9'

services:
  db:
    image: postgres:16
    container_name: eventora_db
    restart: always
    environment:
      POSTGRES_USER: ***REMOVED***
      POSTGRES_PASSWORD: nice try
      POSTGRES_DB: eventora_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
